### ISSUE TITLE
Bro you're a fucking moron if you have to get someone to tell you their user and password

### ISSUE THREAD

**Issue by THECODINGGODNUM1** [eliasyior/prodigy-account-hacker#1]

**Comment by eliasyior** [comment]
bro it's just a joke.

**Comment by THECODINGGODNUM1** [comment]
Bro who the fuck are you?

**Comment by THECODINGGODNUM1** [comment]
WTF u talking to huh?

**Comment by THECODINGGODNUM1** [comment]
Can you take the gift and accept my invitation? Only 2 steps, take your
free gifts from top-notch activity TEMU Free Gifts and help me get mine!
https://temu.com/s/DC70gwnWcwEGQI6k
